import io
import os
from typing import Dict, Any
from datetime import datetime

import docx
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml import OxmlElement
from docx.oxml.ns import qn

# --- Color Constants (RGB) ---
COLOR_PRIMARY = RGBColor(30, 41, 59)      # Slate Navy `#1E293B`
COLOR_VERIFIED = RGBColor(16, 185, 129)   # Legitimate Green `#10B981`
COLOR_LEGIT_LLM = RGBColor(56, 189, 248)  # Legitimate LLM Blue `#38BDF8`
COLOR_REVIEW = RGBColor(139, 92, 246)     # Review Required Purple `#8B5CF6`
COLOR_FAKE = RGBColor(244, 63, 94)        # Suspected Fake Red `#F43F5E`
COLOR_MUTED = RGBColor(100, 116, 139)     # Gray `#64748B`

# --- Helper Functions for styling ---

def set_cell_background(cell, fill_hex: str):
    """Sets background color of a table cell."""
    tcPr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement('w:shd')
    shd.set(qn('w:val'), 'clear')
    shd.set(qn('w:color'), 'auto')
    shd.set(qn('w:fill'), fill_hex)
    tcPr.append(shd)

def add_hyperlink(paragraph, text: str, url: str, color_hex: str = "10B981", underline: bool = True):
    """Adds a clickable hyperlink to a paragraph."""
    part = paragraph.part
    # Register the hyperlink relationship
    r_id = part.relate_to(url, docx.opc.constants.RELATIONSHIP_TYPE.HYPERLINK, is_external=True)

    # Create hyperlink node
    hyperlink = OxmlElement('w:hyperlink')
    hyperlink.set(qn('r:id'), r_id)

    # Create run node
    new_run = OxmlElement('w:r')

    # Create run properties node
    rPr = OxmlElement('w:rPr')

    # Set color
    c = OxmlElement('w:color')
    c.set(qn('w:val'), color_hex)
    rPr.append(c)

    # Set underline
    if underline:
        u = OxmlElement('w:u')
        u.set(qn('w:val'), 'single')
        rPr.append(u)

    new_run.append(rPr)

    # Add text
    text_node = OxmlElement('w:t')
    text_node.text = text
    new_run.append(text_node)

    # Nest inside hyperlink
    hyperlink.append(new_run)
    paragraph._p.append(hyperlink)
    return hyperlink

def format_run(run, font_name: str = "Calibri", size_pt: float = 11, color=None, bold: bool = False, italic: bool = False):
    """Utility to quickly format a run."""
    run.font.name = font_name
    run.font.size = Pt(size_pt)
    if color:
        run.font.color.rgb = color
    run.bold = bold
    run.italic = italic

# --- Core Builder Logic ---

def build_docx_report(results: Dict[str, Any]) -> Document:
    doc = Document()

    # Page Margins (1 inch)
    for section in doc.sections:
        section.top_margin = Inches(1.0)
        section.bottom_margin = Inches(1.0)
        section.left_margin = Inches(1.0)
        section.right_margin = Inches(1.0)

    # --- Title Section ---
    title_p = doc.add_paragraph()
    title_p.paragraph_format.space_before = Pt(0)
    title_p.paragraph_format.space_after = Pt(4)
    title_p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    run_title = title_p.add_run("Literature Review Source Verification Report")
    format_run(run_title, font_name="Calibri Light", size_pt=24, color=COLOR_PRIMARY, bold=True)

    # --- Subtitle / Date ---
    sub_p = doc.add_paragraph()
    sub_p.paragraph_format.space_after = Pt(24)
    run_sub = sub_p.add_run(f"Generated by Literature Review Source Checker on {datetime.now().strftime('%B %d, %Y at %I:%M %p')}")
    format_run(run_sub, font_name="Calibri", size_pt=10, color=COLOR_MUTED, italic=True)

    # --- Section 1: Executive Analytics Summary ---
    sec1_p = doc.add_paragraph()
    sec1_p.paragraph_format.space_before = Pt(12)
    sec1_p.paragraph_format.space_after = Pt(12)
    run_sec1 = sec1_p.add_run("1. Executive Analytics Summary")
    format_run(run_sec1, font_name="Calibri Light", size_pt=16, color=COLOR_PRIMARY, bold=True)

    summary = results.get("summary", {})
    total = summary.get("total_references", 0)
    verified = summary.get("verified", 0)
    legit_llm = summary.get("legitimate_llm", 0)
    review_req = summary.get("review_required", 0)

    # Calculate percentages
    def get_pct(val):
        return f"{(val / total * 100):.1f}%" if total > 0 else "0.0%"

    # Add Summary Table
    table = doc.add_table(rows=5, cols=3)
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    table.style = 'Table Grid'

    # Set headers
    headers = ["Citation Category", "Count", "Percentage"]
    for i, header_text in enumerate(headers):
        cell = table.cell(0, i)
        cell.text = header_text
        set_cell_background(cell, "1E293B")
        for p in cell.paragraphs:
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            for r in p.runs:
                format_run(r, font_name="Calibri", size_pt=11, color=RGBColor(255, 255, 255), bold=True)

    # Populate rows
    rows_data = [
        ("Total References Analyzed", str(total), "100.0%"),
        ("Legitimate (Verified with DOI)", str(verified), get_pct(verified)),
        ("Legitimate (LLM Verified)", str(legit_llm), get_pct(legit_llm)),
        ("Review Required (Unverified/No DOI/Fake)", str(review_req), get_pct(review_req))
    ]

    for row_idx, data in enumerate(rows_data, start=1):
        for col_idx, text in enumerate(data):
            cell = table.cell(row_idx, col_idx)
            cell.text = text
            # Format text
            for p in cell.paragraphs:
                p.paragraph_format.space_after = Pt(4)
                p.paragraph_format.space_before = Pt(4)
                if col_idx == 0:
                    p.alignment = WD_ALIGN_PARAGRAPH.LEFT
                    for r in p.runs:
                        format_run(r, font_name="Calibri", size_pt=10.5, bold=True if row_idx == 4 else False)
                else:
                    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
                    for r in p.runs:
                        format_run(r, font_name="Calibri", size_pt=10.5)

            # Apply alternating light background
            if row_idx % 2 == 0:
                set_cell_background(cell, "F8FAFC")

    # Space after table
    doc.add_paragraph().paragraph_format.space_after = Pt(12)

    # --- Section 2: Detailed Reference Audit ---
    sec2_p = doc.add_paragraph()
    sec2_p.paragraph_format.space_before = Pt(18)
    sec2_p.paragraph_format.space_after = Pt(12)
    run_sec2 = sec2_p.add_run("2. Detailed Reference Audit")
    format_run(run_sec2, font_name="Calibri Light", size_pt=16, color=COLOR_PRIMARY, bold=True)

    references = results.get("references", [])
    for idx, ref in enumerate(references):
        ref_id = ref.get("reference_id", idx + 1)
        raw_ref = ref.get("raw_reference", "")
        status = ref.get("status", "REVIEW_REQUIRED")
        confidence = ref.get("confidence", 0.0)
        metadata = ref.get("matched_metadata")
        llm_verdict = ref.get("llm_verdict")

        # Reference Header
        ref_hdr_p = doc.add_paragraph()
        ref_hdr_p.paragraph_format.space_before = Pt(14)
        ref_hdr_p.paragraph_format.space_after = Pt(4)
        ref_hdr_p.paragraph_format.keep_with_next = True
        
        run_ref_id = ref_hdr_p.add_run(f"Reference #{ref_id} ")
        format_run(run_ref_id, font_name="Calibri", size_pt=12, color=COLOR_PRIMARY, bold=True)

        # Style Status Label
        status_label = "Review Required"
        status_color = COLOR_REVIEW
        if status == "VERIFIED":
            status_label = "Legitimate"
            status_color = COLOR_VERIFIED
        elif status == "LEGITIMATE_KNOWN":
            status_label = "Legitimate (LLM)"
            status_color = COLOR_LEGIT_LLM
        else:
            if llm_verdict and llm_verdict.get("verdict") == "SUSPECTED_FAKE":
                status_label = "Review Required: Suspected Fake"
                status_color = COLOR_FAKE
            elif llm_verdict and llm_verdict.get("verdict") == "UNVERIFIED":
                status_label = "Review Required: Unverified"
                status_color = COLOR_MUTED

        run_status = ref_hdr_p.add_run(f"[{status_label}] ")
        format_run(run_status, font_name="Calibri", size_pt=11, color=status_color, bold=True)

        run_conf = ref_hdr_p.add_run(f"(Confidence: {int(confidence)}%)")
        format_run(run_conf, font_name="Calibri", size_pt=10, color=COLOR_MUTED, italic=True)

        # Raw citation text
        raw_p = doc.add_paragraph()
        raw_p.paragraph_format.left_indent = Inches(0.25)
        raw_p.paragraph_format.space_after = Pt(6)
        run_raw = raw_p.add_run(f'"{raw_ref}"')
        format_run(run_raw, font_name="Calibri", size_pt=10, color=COLOR_MUTED, italic=True)

        # Display metadata if matched
        if metadata:
            meta_p = doc.add_paragraph()
            meta_p.paragraph_format.left_indent = Inches(0.25)
            meta_p.paragraph_format.space_after = Pt(4)
            
            run_lbl = meta_p.add_run("Matched Metadata:\n")
            format_run(run_lbl, font_name="Calibri", size_pt=10, bold=True, color=COLOR_PRIMARY)
            
            # Print title and authors
            m_title = metadata.get("title", "Unknown Title")
            m_authors = metadata.get("authors", "Unknown Authors")
            m_year = metadata.get("year") or "N/A"
            m_journal = metadata.get("journal") or "N/A"
            m_doi = metadata.get("doi")
            m_url = metadata.get("url")

            run_meta = meta_p.add_run(
                f"• Title: {m_title}\n"
                f"• Authors: {m_authors}\n"
                f"• Year: {m_year}\n"
                f"• Journal: {m_journal}\n"
            )
            format_run(run_meta, font_name="Calibri", size_pt=9.5)

            # Verification Link
            link_p = doc.add_paragraph()
            link_p.paragraph_format.left_indent = Inches(0.25)
            link_p.paragraph_format.space_after = Pt(6)
            run_link_lbl = link_p.add_run("• Verification Link: ")
            format_run(run_link_lbl, font_name="Calibri", size_pt=9.5)

            if m_doi:
                doi_url = f"https://doi.org/{m_doi}"
                add_hyperlink(link_p, doi_url, doi_url, color_hex="10B981")
            elif m_url:
                add_hyperlink(link_p, "View Article Link", m_url, color_hex="10B981")
            else:
                run_no_link = link_p.add_run("N/A")
                format_run(run_no_link, font_name="Calibri", size_pt=9.5, italic=True)

        # Display LLM Verdict Reasoning
        if llm_verdict and llm_verdict.get("reasoning"):
            reason_p = doc.add_paragraph()
            reason_p.paragraph_format.left_indent = Inches(0.25)
            reason_p.paragraph_format.space_after = Pt(12)
            
            v_title = "Audit Verdict"
            if llm_verdict.get("verdict") == "SUSPECTED_FAKE":
                v_title = "Audit Verdict: Suspected Fake Citation"
                lbl_color = COLOR_FAKE
            elif status == "VERIFIED" or llm_verdict.get("is_match") is True:
                v_title = "Audit Verdict: Verified Legitimate"
                lbl_color = COLOR_VERIFIED
            else:
                lbl_color = COLOR_PRIMARY

            run_v_lbl = reason_p.add_run(f"• {v_title}:\n")
            format_run(run_v_lbl, font_name="Calibri", size_pt=10, bold=True, color=lbl_color)

            run_reason = reason_p.add_run(f"{llm_verdict['reasoning']}")
            format_run(run_reason, font_name="Calibri", size_pt=9.5)

    return doc

def generate_docx_report(results: Dict[str, Any], output_path: str):
    """Helper to build and save a DOCX report to file."""
    doc = build_docx_report(results)
    doc.save(output_path)
    print(f"Saved DOCX report to: {output_path}")
